export const WINDOWS_ECMA_KEYMAP: Record<string, number> = {
  'Backspace': 0x08,
  'Tab': 0x09,
  'Enter': 0x0D,
  'ShiftLeft': 0xA0,
  'ShiftRight': 0xA1,
  'ControlLeft': 0xA2,
  'ControlRight': 0xA3,
  'AltLeft': 0xA4,
  'AltRight': 0xA5,
  'Pause': 0x13,
  'CapsLock': 0x14,
  'Escape': 0x1B,
  'Space': 0x20,
  'PageUp': 0x21,
  'PageDown': 0x22,
  'End': 0x23,
  'Home': 0x24,
  'ArrowLeft': 0x25,
  'ArrowUp': 0x26,
  'ArrowRight': 0x27,
  'ArrowDown': 0x28,
  'PrintScreen': 0x2C,
  'Insert': 0x2D,
  'Delete': 0x2E,

  'Digit0': 0x30,
  'Digit1': 0x31,
  'Digit2': 0x32,
  'Digit3': 0x33,
  'Digit4': 0x34,
  'Digit5': 0x35,
  'Digit6': 0x36,
  'Digit7': 0x37,
  'Digit8': 0x38,
  'Digit9': 0x39,

  'a': 0x41,
  'b': 0x42,
  'c': 0x43,
  'd': 0x44,
  'e': 0x45,
  'f': 0x46,
  'g': 0x47,
  'h': 0x48,
  'i': 0x49,
  'j': 0x4A,
  'k': 0x4B,
  'l': 0x4C,
  'm': 0x4D,
  'n': 0x4E,
  'o': 0x4F,
  'p': 0x50,
  'q': 0x51,
  'r': 0x52,
  's': 0x53,
  't': 0x54,
  'u': 0x55,
  'v': 0x56,
  'w': 0x57,
  'x': 0x58,
  'y': 0x59,
  'z': 0x5A,

  'Meta': 0x5B,
  'ContextMenu': 0x5D,
  'Numpad0': 0x60,
  'Numpad1': 0x61,
  'Numpad2': 0x62,
  'Numpad3': 0x63,
  'Numpad4': 0x64,
  'Numpad5': 0x65,
  'Numpad6': 0x66,
  'Numpad7': 0x67,
  'Numpad8': 0x68,
  'Numpad9': 0x69,
  'Multiply': 0x6A,
  'Add': 0x6B,
  'Subtract': 0x6D,
  'Decimal': 0x6E,
  'Divide': 0x6F,

  'F1': 0x70,
  'F2': 0x71,
  'F3': 0x72,
  'F4': 0x73,
  'F5': 0x74,
  'F6': 0x75,
  'F7': 0x76,
  'F8': 0x77,
  'F9': 0x78,
  'F10': 0x79,
  'F11': 0x7A,
  'F12': 0x7B,

  'NumLock': 0x90,
  'ScrollLock': 0x91,
  ';': 0xBA,
  '=': 0xBB,
  ',': 0xBC,
  '-': 0xBD,
  '.': 0xBE,
  '/': 0xBF,
  '`': 0xC0,
  '[': 0xDB,
  '\\': 0xDC,
  ']': 0xDD,
  "'": 0xDE,
  // Add more mappings as needed
}


const FACE_BUTTONS: Record<string, number> = {
  DPAD_UP: 0x0001,
  DPAD_DOWN: 0x0002,
  DPAD_LEFT: 0x0004,
  DPAD_RIGHT: 0x0008,
  START: 0x0010,
  BACK: 0x0020,
  LEFT_THUMB: 0x0040,
  RIGHT_THUMB: 0x0080,
  LEFT_SHOULDER: 0x0100,
  RIGHT_SHOULDER: 0x0200,
  GUIDE: 0x0400,
  A: 0x1000,
  B: 0x2000,
  X: 0x4000,
  Y: 0x8000,
};

const STICK_DISTANCE = 29000;
const TRIGGER_DISTANCE = 255;

export const CONTROLLER_INPUTS: Record<string, { result_type: string; result_value: number }> = {
  'DPAD UP': { result_type: 'face_button', result_value: FACE_BUTTONS.DPAD_UP },
  'DPAD DOWN': { result_type: 'face_button', result_value: FACE_BUTTONS.DPAD_DOWN },
  'DPAD LEFT': { result_type: 'face_button', result_value: FACE_BUTTONS.DPAD_LEFT },
  'DPAD RIGHT': { result_type: 'face_button', result_value: FACE_BUTTONS.DPAD_RIGHT },
  'START': { result_type: 'face_button', result_value: FACE_BUTTONS.START },
  'BACK': { result_type: 'face_button', result_value: FACE_BUTTONS.BACK },
  'LEFT THUMB': { result_type: 'face_button', result_value: FACE_BUTTONS.LEFT_THUMB },
  'RIGHT THUMB': { result_type: 'face_button', result_value: FACE_BUTTONS.RIGHT_THUMB },
  'LEFT SHOULDER': { result_type: 'face_button', result_value: FACE_BUTTONS.LEFT_SHOULDER },
  'RIGHT SHOULDER': { result_type: 'face_button', result_value: FACE_BUTTONS.RIGHT_SHOULDER },
  'GUIDE': { result_type: 'face_button', result_value: FACE_BUTTONS.GUIDE },
  'A': { result_type: 'face_button', result_value: FACE_BUTTONS.A },
  'B': { result_type: 'face_button', result_value: FACE_BUTTONS.B },
  'X': { result_type: 'face_button', result_value: FACE_BUTTONS.X },
  'Y': { result_type: 'face_button', result_value: FACE_BUTTONS.Y },
  'LEFT STICK UP': { result_type: 'thumb_ly', result_value: STICK_DISTANCE },
  'LEFT STICK DOWN': { result_type: 'thumb_ly', result_value: -STICK_DISTANCE },
  'LEFT STICK LEFT': { result_type: 'thumb_lx', result_value: -STICK_DISTANCE },
  'LEFT STICK RIGHT': { result_type: 'thumb_lx', result_value: STICK_DISTANCE },
  'RIGHT STICK UP': { result_type: 'thumb_ry', result_value: STICK_DISTANCE },
  'RIGHT STICK DOWN': { result_type: 'thumb_ry', result_value: -STICK_DISTANCE },
  'RIGHT STICK LEFT': { result_type: 'thumb_rx', result_value: -STICK_DISTANCE },
  'RIGHT STICK RIGHT': { result_type: 'thumb_rx', result_value: STICK_DISTANCE },
  'LEFT TRIGGER': { result_type: 'trigger_l', result_value: TRIGGER_DISTANCE },
  'RIGHT TRIGGER': { result_type: 'trigger_r', result_value: TRIGGER_DISTANCE },
};